# Web服务配置
server:
  port: 8080

# MySQL数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 101807
    url: jdbc:mysql://localhost:3306/my_db?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai


# Redis配置
  data:
    redis:
      host: 172.27.126.128
      port: 6379
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

# Swagger配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: order
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      display-name: '初始化项目'
      paths-to-match: '/**'
      packages-to-scan: com.pandaer.project
  default-flat-param-object: true

